### ISSUE TITLE
It does not work in 2.1.24b6.

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/ReMemorizeButtons#12]
It does not work in 2.1.24b6.

Anki 2.1.24 (394f7c63) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-19 17:26:50

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 459, in handler
  File "aqt\reviewer.py", line 540, in _onTypedAnswer
  File "aqt\reviewer.py", line 243, in _showAnswer
  File "<D:\Anki\Anki.2.1.24b6\decorator.pyc:decorator-gen-6>", line 2, in _showEaseButtons
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 629, in repl
  File "aqt\reviewer.py", line 598, in _showEaseButtons
  File "aqt\reviewer.py", line 654, in _answerButtons
TypeError: 'NoneType' object is not iterable

**Comment by lovac42** [comment]
I can't reproduce this on beta7. Seems to work just fine. If you still experience this on beta7, post your config settings.

**Comment by cjdduarte** [comment]
I have now installed beta8. It is working.
Thanks.
